name: SharpGit

on: [push]

env:
  # Path to the solution file relative to the root of the Project.
  SOLUTION_FILE_PATH: SharpGit/src/SharpGit.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
      with:
        path: SharpGit

    - name: Build Dependencies via VCPKG
      uses: lukka/run-vcpkg@v7
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgGitCommitId: 4278a5f9eafbdadfaa65d7aafd914964841cba42
        vcpkgArguments: libgit2:x64-windows-static-md libgit2:x86-windows-static-md apr-util:x64-windows-static-md apr-util:x86-windows-static-md libssh2:x64-windows-static-md libssh2:x86-windows-static-md
        additionalCachedPaths: ${{ env.buildDir }}/vcpkg_installed

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
      
    - name: Restore NuGet package (legacy style, vcxproj only)
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore SharpGit\src\SharpGit\SharpGit.vcxproj -SolutionDirectory SharpGit\src

    - name: Build-x86
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /restore /p:Platform=x86 /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Build-x64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /restore /p:Platform=x64 /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: VSTest-x86
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: vstest.console.exe /InIsolation /Platform:x86 SharpGit/src/SharpGit.Tests/bin/x86/Release/SharpGit.Tests.dll "--testcasefilter:TestCategory!=NeedsNetwork"

    - name: VSTest-x64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: vstest.console.exe /InIsolation /Platform:x64 SharpGit/src/SharpGit.Tests/bin/x64/Release/SharpGit.Tests.dll "--testcasefilter:TestCategory!=NeedsNetwork"
